name: destroy_sns

on:
  workflow_dispatch:
    inputs:
      sns_topic_name:
        description: 'SNS Topic Name'
        required: true
      region:
        description: 'AWS Region'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  terraform_apply:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Assume AWS Role using OIDC
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: arn:aws:iam::730335384723:role/backstage_interns_project
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ github.event.inputs.region }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      working-directory: ./delete_sns
      run: terraform init


    - name: Terraform Destroy
      working-directory: ./delete_sns
      run: |
        terraform destroy -var sns_topic_name=${{ github.event.inputs.sns_topic_name }} -var region=${{ github.event.inputs.region }} -auto-approve
            
